apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-arc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-k8s-arc
  template:
    metadata:
      labels:
        app: hello-k8s-arc
    spec:
      containers:
      - name: hello-k8s-arc
        image: atanudochub/helloazurearc:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I just deployed this on Kubernetes!

---------

apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-arc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-k8s-arc