apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arc-deployment
  labels:
    app: hello-arc
spec:
  replicas: 3
  template:
    metadata:
      name: hello-arc
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: atanudochub/helloazurearc:latest
      restartPolicy: Always
  selector:
    matchLabels:
      app: hello-arc

---

apiVersion: v1
kind: Service
metadata:
  name: hello-arc-service
spec:
  selector:
    app: hello-arc
  ports:
    - port: 80
  type: LoadBalancer
  
  