apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-arc
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: atanudochub/helloazurearc
        tag: latest
        ports:
        - containerPort: 8080

--------

apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-arc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-arc

