apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-arc
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: atanudochub/helloazurearc
        tag: latest
        ports:
        - containerPort: 8080